import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { usePageMeta } from "@/hooks/use-page-meta";
import {
  Star, Send, BarChart2, MessageSquare, Mail, Smartphone,
  CheckCircle2, ChevronDown, ChevronUp, Menu, X, ArrowRight,
  Zap, Shield, Users, Globe, Video, Bell
} from "lucide-react";
import { FaInstagram, FaLinkedin, FaFacebook } from "react-icons/fa";

const PRIMARY = "#0E679D";

const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "How It Works", href: "#how-it-works" },
  { label: "Pricing", href: "#pricing" },
  { label: "FAQ", href: "#faq" },
];

const PAIN_POINTS = [
  {
    icon: <MessageSquare className="w-6 h-6" style={{ color: PRIMARY }} />,
    heading: "Asking feels awkward",
    body: "Most business owners feel uncomfortable asking customers for a review face to face — so they simply don't.",
  },
  {
    icon: <Bell className="w-6 h-6" style={{ color: PRIMARY }} />,
    heading: "Customers forget",
    body: "Even when customers say they'll leave a review, life gets in the way. Without a follow-up, it never happens.",
  },
  {
    icon: <Globe className="w-6 h-6" style={{ color: PRIMARY }} />,
    heading: "Competitors get ahead",
    body: "Businesses with more reviews rank higher, get more clicks, and win more customers — even if your service is better.",
  },
];

const STEPS = [
  {
    number: "01",
    heading: "Add your customer",
    body: "Enter a customer's name, email, or phone number — or import a list in bulk. ReviewOptic keeps track of everyone you've served.",
  },
  {
    number: "02",
    heading: "Send a personalised request",
    body: "Choose email, SMS, or WhatsApp. ReviewOptic sends a personalised message with your name and their service — not a generic template that gets ignored.",
  },
  {
    number: "03",
    heading: "Sit back and collect reviews",
    body: "If they don't respond, ReviewOptic follows up automatically — up to 3 times. You do nothing. The reviews come in.",
  },
];

const FEATURES = [
  { icon: <Mail className="w-5 h-5" />, title: "Email, SMS & WhatsApp", body: "Reach customers on the channel they actually use." },
  { icon: <Zap className="w-5 h-5" />, title: "AI-Powered Messages", body: "Personalised messages generated by AI — not copy-paste templates." },
  { icon: <Bell className="w-5 h-5" />, title: "Automatic Follow-Ups", body: "Up to 3 follow-ups per customer, sent on autopilot." },
  { icon: <BarChart2 className="w-5 h-5" />, title: "Full Analytics", body: "Track conversion rates, best send times, and which channels perform best." },
  { icon: <Shield className="w-5 h-5" />, title: "Private Feedback", body: "Unhappy customers are redirected privately — protecting your public rating." },
  { icon: <Globe className="w-5 h-5" />, title: "Works Everywhere", body: "Google, Trustpilot, Facebook, Checkatrade, TripAdvisor, and more." },
  { icon: <Video className="w-5 h-5" />, title: "Voice & Video Messages", body: "Record a personal message that plays when your customer opens the request." },
  { icon: <Users className="w-5 h-5" />, title: "Team Access", body: "Invite your team to send requests and track their performance individually." },
  { icon: <Smartphone className="w-5 h-5" />, title: "QR Code & Widget", body: "Collect reviews in-person with a QR code, or display them on your website." },
];

const PLANS = [
  {
    name: "Standard",
    price: "£29",
    period: "/month",
    description: "Perfect for getting started",
    limit: "Up to 10 review requests per month",
    highlight: false,
  },
  {
    name: "Pro",
    price: "£39",
    period: "/month",
    description: "For businesses serious about reviews",
    limit: "Unlimited review requests per month",
    highlight: true,
  },
];

const SHARED_FEATURES = [
  "Email, SMS & WhatsApp review requests",
  "Automatic follow-ups — all 3 included",
  "AI-generated & custom message templates",
  "Full analytics dashboard",
  "Private feedback capture",
  "Website review widget & QR code",
  "Works with Google, Trustpilot, Facebook & more",
  "No contracts — cancel anytime",
];

const FAQS = [
  { q: "How does the free trial work?", a: "Every new account gets a 30-day free trial with full access. You won't be charged until the trial ends — and you can cancel anytime before then." },
  { q: "Do I need a credit card to sign up?", a: "Yes, you'll need to enter payment details when selecting your plan. Nothing is charged until your 30-day free trial ends — and you can cancel anytime before then." },
  { q: "What platforms does ReviewOptic work with?", a: "Google, Trustpilot, Facebook, Checkatrade, TripAdvisor, MyBuilder, and any other platform with a direct review link." },
  { q: "What's the difference between Standard and Pro?", a: "Standard allows up to 10 review requests per month. Pro gives you unlimited requests and team member access. All other features are included on both plans." },
  { q: "Do follow-ups count toward my monthly limit?", a: "No. Only the initial request counts. Automatic follow-ups (up to 3 per customer) are sent on top of that at no extra cost." },
  { q: "Will my price ever increase?", a: "Not while you stay subscribed. We guarantee your price never increases as long as your subscription remains active." },
];

function scrollTo(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
}

export default function Home() {
  usePageMeta(
    "ReviewOptic — Get More 5-Star Reviews Without the Awkward Asking",
    "ReviewOptic makes it effortless for UK businesses to collect 5-star reviews via email, SMS & WhatsApp — with automatic follow-ups and AI-powered messages. 30-day free trial.",
    "/"
  );

  const [, navigate] = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 10);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">

      {/* ── NAV ── */}
      <nav className={`fixed top-0 left-0 right-0 z-50 bg-white transition-all duration-200 ${scrolled ? "shadow-sm border-b border-gray-100" : ""}`}>
        <div className="relative max-w-6xl mx-auto px-5 flex flex-col">

          {/* Top row: logo + CTAs + socials */}
          <div className="flex items-center justify-between py-3">
            <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center">
              <img src="/logo.png" alt="ReviewOptic" className="h-20 w-auto object-contain" />
            </button>

            <div className="hidden md:flex items-center gap-3">
              <button onClick={() => navigate("/login")} className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors px-3 py-1">
                Sign In
              </button>
              <button onClick={() => navigate("/register")} className="text-sm font-semibold text-white px-4 py-1.5 rounded-lg transition-opacity hover:opacity-90" style={{ backgroundColor: PRIMARY }}>
                Start Free Trial
              </button>
              <div className="w-px h-5 bg-gray-200 mx-1" />
              <a href="https://www.instagram.com/reviewopticapp/" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-700 transition-colors p-1">
                <FaInstagram size={16} />
              </a>
              <a href="https://www.linkedin.com/company/reviewoptic" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-700 transition-colors p-1">
                <FaLinkedin size={16} />
              </a>
              <a href="https://www.facebook.com/reviewopticapp/" target="_blank" rel="noopener noreferrer" className="text-gray-400 hover:text-gray-700 transition-colors p-1">
                <FaFacebook size={16} />
              </a>
            </div>

            <button className="md:hidden p-2 text-gray-600" onClick={() => setMenuOpen(o => !o)}>
              {menuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>

          {/* Bottom row: page links, truly centred */}
          <div className="hidden md:flex items-center justify-center gap-7 pb-2">
            {NAV_LINKS.map(l => (
              <button key={l.label} onClick={() => scrollTo(l.href.slice(1))} className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
                {l.label}
              </button>
            ))}
          </div>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="md:hidden bg-white border-t border-gray-100 px-5 py-4 flex flex-col gap-4">
            {NAV_LINKS.map(l => (
              <button key={l.label} onClick={() => { scrollTo(l.href.slice(1)); setMenuOpen(false); }} className="text-sm font-medium text-gray-700 text-left">
                {l.label}
              </button>
            ))}
            <hr className="border-gray-100" />
            <button onClick={() => navigate("/login")} className="text-sm font-medium text-gray-700 text-left">Sign In</button>
            <button onClick={() => navigate("/register")} className="text-sm font-semibold text-white px-4 py-2.5 rounded-lg w-full" style={{ backgroundColor: PRIMARY }}>
              Start Free Trial
            </button>
          </div>
        )}
      </nav>

      {/* ── HERO ── */}
      <section className="pt-52 pb-24 px-5 text-white text-center" style={{ backgroundColor: PRIMARY }}>
        <div className="max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 bg-white/15 border border-white/25 rounded-full px-4 py-1.5 text-sm font-medium mb-6">
            <Star className="w-3.5 h-3.5 fill-white" />
            30-day free trial — cancel anytime
          </div>
          <h1 className="font-black leading-snug tracking-tight mb-8 drop-shadow-md" style={{ fontSize: "clamp(1.5rem, 2.8vw, 3rem)" }}>
            Most Businesses Have Happy Customers.<br /> Few Have the Reviews to Prove It.
          </h1>
          <p className="text-lg sm:text-xl text-white/85 leading-relaxed max-w-2xl mx-auto mb-10">
            ReviewOptic makes it effortless to ask — so the reviews actually come in. Email, SMS, WhatsApp. Automatic follow-ups. AI-powered messages. All on autopilot.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <button onClick={() => navigate("/register")} className="flex items-center justify-center gap-2 bg-white font-semibold px-7 py-3.5 rounded-xl text-base hover:bg-gray-50 transition-colors" style={{ color: PRIMARY }}>
              Start Your Free Trial <ArrowRight className="w-4 h-4" />
            </button>
            <button onClick={() => scrollTo("how-it-works")} className="flex items-center justify-center gap-2 border border-white/40 text-white font-medium px-7 py-3.5 rounded-xl text-base hover:bg-white/10 transition-colors">
              See How It Works
            </button>
          </div>

          {/* Video placeholder */}
          <div className="mt-14 rounded-2xl border border-white/20 bg-white/10 backdrop-blur aspect-video max-w-2xl mx-auto flex items-center justify-center">
            <div className="text-center">
              <div className="w-14 h-14 rounded-full bg-white/20 border border-white/30 flex items-center justify-center mx-auto mb-3">
                <Video className="w-6 h-6 text-white" />
              </div>
              <p className="text-white/70 text-sm">Product video coming soon</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── THE PROBLEM ── */}
      <section className="py-20 px-5 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Why Most Businesses Don't Get Reviews</h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto">It's not that your customers are unhappy. It's that the process is broken.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {PAIN_POINTS.map((p, i) => (
              <div key={i} className="bg-white rounded-2xl p-7 border border-gray-100 shadow-sm">
                <div className="mb-4">{p.icon}</div>
                <h3 className="font-semibold text-gray-900 text-lg mb-2">{p.heading}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{p.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section id="how-it-works" className="py-20 px-5 bg-white">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">How ReviewOptic Works</h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto">Three simple steps. Then ReviewOptic handles everything else.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {STEPS.map((s, i) => (
              <div key={i} className="relative">
                <div className="text-5xl font-black mb-4 opacity-10 leading-none" style={{ color: PRIMARY }}>{s.number}</div>
                <h3 className="font-bold text-gray-900 text-xl mb-3">{s.heading}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{s.body}</p>
                {i < STEPS.length - 1 && (
                  <div className="hidden md:block absolute top-6 right-0 translate-x-1/2 text-gray-200 text-2xl">→</div>
                )}
              </div>
            ))}
          </div>

          {/* Video placeholder */}
          <div className="mt-14 rounded-2xl border border-gray-200 bg-gray-50 aspect-video max-w-2xl mx-auto flex items-center justify-center">
            <div className="text-center">
              <div className="w-14 h-14 rounded-full bg-gray-200 flex items-center justify-center mx-auto mb-3">
                <Video className="w-6 h-6 text-gray-400" />
              </div>
              <p className="text-gray-400 text-sm">Walkthrough video coming soon</p>
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section id="features" className="py-20 px-5 bg-gray-50">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Everything You Need to Dominate Your Reviews</h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto">ReviewOptic isn't just a message sender. It's a full review growth system.</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map((f, i) => (
              <div key={i} className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center mb-4 text-white" style={{ backgroundColor: PRIMARY }}>
                  {f.icon}
                </div>
                <h3 className="font-semibold text-gray-900 mb-1.5">{f.title}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{f.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section id="pricing" className="py-20 px-5 bg-white">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Simple, Transparent Pricing</h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto">No setup fees. No long contracts. Cancel anytime. Start with a 30-day free trial.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-2xl mx-auto">
            {PLANS.map((plan, i) => (
              <div key={i} className={`rounded-2xl border p-8 flex flex-col ${plan.highlight ? "border-2 shadow-lg relative" : "border-gray-200"}`} style={plan.highlight ? { borderColor: PRIMARY } : {}}>
                {plan.highlight && (
                  <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 text-white text-xs font-semibold px-4 py-1 rounded-full" style={{ backgroundColor: PRIMARY }}>
                    Most Popular
                  </div>
                )}
                <div className="mb-6">
                  <h3 className="text-xl font-bold text-gray-900 mb-1">{plan.name}</h3>
                  <p className="text-gray-500 text-sm mb-4">{plan.description}</p>
                  <div className="flex items-baseline gap-1">
                    <span className="text-4xl font-extrabold text-gray-900">{plan.price}</span>
                    <span className="text-gray-400 text-sm">{plan.period}</span>
                  </div>
                  <p className="text-sm mt-2 font-medium" style={{ color: PRIMARY }}>{plan.limit}</p>
                </div>
                <ul className="space-y-2.5 mb-8 flex-1">
                  {SHARED_FEATURES.map((f, j) => (
                    <li key={j} className="flex items-start gap-2.5 text-sm text-gray-600">
                      <CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5" style={{ color: PRIMARY }} />
                      {f}
                    </li>
                  ))}
                </ul>
                <button onClick={() => navigate("/register")} className={`w-full py-3 rounded-xl font-semibold text-sm transition-opacity hover:opacity-90 ${plan.highlight ? "text-white" : "border-2"}`} style={plan.highlight ? { backgroundColor: PRIMARY } : { borderColor: PRIMARY, color: PRIMARY }}>
                  Start Free Trial
                </button>
              </div>
            ))}
          </div>
          <p className="text-center text-gray-400 text-sm mt-6">Annual billing available — save the equivalent of 1 month per year.</p>
        </div>
      </section>

      {/* ── FAQ ── */}
      <section id="faq" className="py-20 px-5 bg-gray-50">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
          </div>
          <div className="space-y-3">
            {FAQS.map((faq, i) => (
              <div key={i} className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                <button className="w-full flex items-center justify-between px-6 py-4 text-left" onClick={() => setOpenFaq(openFaq === i ? null : i)}>
                  <span className="font-medium text-gray-900 text-sm">{faq.q}</span>
                  {openFaq === i ? <ChevronUp className="w-4 h-4 text-gray-400 shrink-0" /> : <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />}
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-5 text-sm text-gray-500 leading-relaxed border-t border-gray-50 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <section className="py-24 px-5 text-white text-center" style={{ backgroundColor: PRIMARY }}>
        <div className="max-w-2xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-bold mb-4">Ready to Start Getting More Reviews?</h2>
          <p className="text-white/80 text-lg mb-10">Join businesses across the UK growing their reputation on autopilot. 30-day free trial. Cancel anytime.</p>
          <button onClick={() => navigate("/register")} className="inline-flex items-center gap-2 bg-white font-semibold px-8 py-4 rounded-xl text-base hover:bg-gray-50 transition-colors" style={{ color: PRIMARY }}>
            Start Your Free Trial <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="bg-gray-900 text-gray-400 py-10 px-5">
        <div className="max-w-6xl mx-auto text-sm text-center space-y-3">
          <div className="flex flex-wrap justify-center gap-5">
            <button onClick={() => navigate("/privacy")} className="hover:text-white transition-colors">Privacy Policy</button>
            <button onClick={() => navigate("/terms")} className="hover:text-white transition-colors">Terms & Conditions</button>
            <button onClick={() => navigate("/pricing")} className="hover:text-white transition-colors">Pricing</button>
            <button onClick={() => navigate("/faq")} className="hover:text-white transition-colors">FAQ</button>
          </div>
          <p>© {new Date().getFullYear()} ReviewOptic Limited &nbsp;·&nbsp; <a href="mailto:hello@reviewoptic.com" className="hover:text-white transition-colors">hello@reviewoptic.com</a></p>
        </div>
      </footer>

    </div>
  );
}
